@startuml

state Dealer {
[*] -> IS_SHUFFLED
IS_SHUFFLED -down-> OFFER_FICHES: QUIT
IS_SHUFFLED: start : +1000 balance
IS_SHUFFLED: offer : +500 balance
note right of IS_SHUFFLED: Games\n HIGHLOW\n- simple double or nothing\n- three in a row
IS_SHUFFLED -down-> HAS_HUMAN: POST_INIT
HAS_HUMAN --> IS_SHUFFLED: PUT_TURN
HAS_HUMAN: select # bots
HAS_HUMAN --> CardGame: POST_INIT_HUMAN
OFFER_FICHES -up-> IS_SHUFFLED: OFFER_ACCEPTED
OFFER_FICHES --> [*]

state CardGame {
[*] -> TURN_STARTED
TURN_STARTED --> TURN_STARTED: PLAYER_PASSES
TURN_STARTED --> GAME_WON: TURN_STARTED
TURN_STARTED --> NO_WINNER: NO_CARDS_LEFT \n or ROUNDS_ENDED
GAME_WON --> GAME_WON: SHOW_RESULTS
GAME_WON --> TURN_STARTED: TURN_ENDED
GAME_WON --> NO_WINNER: NO_CARDS_LEFT \n or PLAYERS_WINS
NO_WINNER -up-> IS_SHUFFLED: GAME_FINISHED
}
}
@enduml