DROP TABLE IF EXISTS "league";
DROP TABLE IF EXISTS "result";

DROP TABLE IF EXISTS "cardmove";
DROP TABLE IF EXISTS "playing";
DROP TABLE IF EXISTS "player";
DROP TABLE IF EXISTS "card";
DROP TABLE IF EXISTS "game";

DROP TABLE IF EXISTS "roles_privileges";
DROP TABLE IF EXISTS "privilege";
DROP TABLE IF EXISTS "role";
DROP TABLE IF EXISTS "users_roles";
DROP TABLE IF EXISTS "visitor";
