create table if not exists "visitor" (
"visitor_id" bigint generated by default as identity,
"created" varchar(25),
"username" varchar(25) not null unique,
"password" varchar(60),
"alias" varchar(50) not null,
"alias_seq" integer,
"email" varchar(50) not null,
"balance" integer,
"secured_loan" integer, "week" varchar(3),
"enabled" boolean not null,
"is_using2fa" boolean not null,
"year" integer,
"month" tinyint check ("month" between 0 and 11),
"weekday" integer,
primary key ("visitor_id")
);

create table if not exists "role" (
"role_id" bigint not null,
"name" varchar(255),
primary key ("role_id")
);
create table if not exists "users_roles" (
"role_id" bigint not null,
"visitor_id" bigint not null
);

create table if not exists "privilege" (
"privilege_id" bigint not null,
"name" varchar(25),
primary key ("privilege_id")
);
create table if not exists "roles_privileges" (
"privilege_id" bigint not null,
"role_id" bigint not null
);

create table if not exists "league" (
"league_id" bigint generated by default as identity,
"created" varchar(25),
"name" varchar(50) not null,
"name_seq" integer,
"visitor_id" bigint not null,
"is_active" boolean,
"ended" varchar(25),
primary key ("league_id")
);
create table if not exists "game" (
"game_id" bigint generated by default as identity,
"updated" varchar(25) not null,
"type" varchar(50) not null check ("type" in ('HIGHLOW','BLACKJACK','ERROR')),
"state" varchar(50) not null check ("state" in ('INITIALIZED','PENDING_INVITATIONS','PREPARED','STARTED','INITIATOR_MOVE','INVITEE_MOVE','BOT_MOVE','FINISHED','QUIT','CANCELLED','ERROR')),
"previous_state" varchar(50) check ("previous_state" in ('INITIALIZED','PENDING_INVITATIONS','PREPARED','STARTED','INITIATOR_MOVE','INVITEE_MOVE','BOT_MOVE','FINISHED','QUIT','CANCELLED','ERROR')),
"style" varchar(10),
"ante" integer,
"year" integer,
"month" tinyint check ("month" between 0 and 11),
"week" varchar(3),
"weekday" integer,
"initiator" bigint,
"league_id" bigint,
primary key ("game_id")
);
create table if not exists "player" (
"player_id" bigint generated by default as identity,
"created" varchar(25),
"seat" integer,
"game_id" bigint,
"fiches" integer,
"is_human" boolean,
"is_winner" boolean,
"ai_level" varchar(50) check ("ai_level" in ('DUMB','AVERAGE','SMART','HUMAN','ERROR')),
"avatar" varchar(50) check ("avatar" in ('ELF','MAGICIAN','GOBLIN','ROMAN','ERROR')),
"avatar_name" varchar(50),
"role" varchar(20) not null check ("role" in ('INITIATOR','INVITED','ACCEPTED','REJECTED','BOT','ERROR')),
"visitor_id" bigint,
primary key ("player_id")
);

create table if not exists "card" (
"card_id" bigint generated by default as identity,
"rank_suit" varchar(3) not null,
"sequence" integer,
"game_id" bigint not null,
"player_id" bigint,
"created" varchar(25),
"face" varchar(255) not null check ("face" in ('UP','DOWN','ERROR')),
"location" varchar(255) not null check ("location" in ('PACK','STOCK','STACK','HAND','PILE_1','PILE_2','TABLEAU_1','WASTEPILE','ERROR')),
"position" varchar(255) not null check ("position" in ('SHUFFLED','ORDERED','MANUAL','ERROR')),
primary key ("card_id")
);

create table if not exists "playing" (
"playing_id" bigint generated by default as identity,
"created" varchar(25),
"player_id" bigint,
"game_id" bigint not null unique,
"current_round_number" integer,
"current_seat_number" integer,
"current_move_number" integer,
"year" integer,
"month" tinyint check ("month" between 0 and 11),
"week" varchar(3),
"weekday" integer,
primary key ("playing_id")
);
create table if not exists "cardmove" (
"cardmove_id" bigint generated by default as identity,
"created" varchar(25),
"card_move_details" varchar(255),
"player_id" bigint,
"playing_id" bigint,
"card_id" bigint,
"bet" integer,
"end_fiches" integer,
"start_fiches" integer,
"location" varchar(255) check ("location" in ('PACK','STOCK','STACK','HAND','PILE_1','PILE_2','TABLEAU_1','WASTEPILE','ERROR')), "move" varchar(255) not null check ("move" in ('DEAL','PASS','NEXT','STOP','PLAY','STAND','DOUBLE','HIGHER','LOWER','ERROR')),
"sequence" varchar(255),
primary key ("cardmove_id")
);

create table if not exists "result" (
"result_id" bigint generated by default as identity,
"created" varchar(25),
"game_id" bigint not null,
"player_id" bigint not null unique,
"visitor_id" bigint,
"fiches_won" integer,
"month" tinyint check ("month" between 0 and 11),
"week" varchar(3),
"weekday" integer,
"winner" boolean, "year" integer,
"type" varchar(50) not null check ("type" in ('HIGHLOW','BLACKJACK','ERROR')),
primary key ("result_id")
);

create index if not exists "cards_game_index" on "card" ("game_id");
create index if not exists "alias_index" on "visitor" ("alias");

alter table if exists "card" add constraint if not exists fk_game_id foreign key ("game_id") references "game";

alter table if exists "cardmove" add constraint if not exists fk_playing_id foreign key ("playing_id") references "playing";
alter table if exists "game" add constraint if not exists fk_league_id foreign key ("league_id") references "league";
alter table if exists "league" add constraint if not exists fk_visitor_id foreign key ("visitor_id") references "visitor";

alter table if exists "player" add constraint if not exists fk_game_id foreign key ("game_id") references "game";
alter table if exists "player" add constraint if not exists fk_visitor_id foreign key ("visitor_id") references "visitor";

alter table if exists "result" add constraint if not exists fk_game_id foreign key ("game_id") references "game";
alter table if exists "result" add constraint if not exists fk_player_id foreign key ("player_id") references "player";
alter table if exists "result" add constraint if not exists fk_visitor_id foreign key ("visitor_id") references "visitor";

alter table if exists "playing" add constraint if not exists fk_player_id foreign key ("player_id") references "player";
alter table if exists "playing" add constraint if not exists fk_game_id foreign key ("game_id") references "game";

alter table if exists "roles_privileges" add constraint if not exists "FKqdkx0p2y8beq5lgy8gkd5p0x" foreign key ("privilege_id") references "privilege";
alter table if exists "roles_privileges" add constraint if not exists "FKf9g87v3a8i8cym8qc8jvu1jyb" foreign key ("role_id") references "role";

alter table if exists "users_roles" add constraint if not exists "FKjticpblwpgkc74xs0dvirhdtr" foreign key ("role_id") references "role";
alter table if exists "users_roles" add constraint if not exists "FK2b45blclate4s8l1pal3hlf6x" foreign key ("visitor_id") references "visitor";
